# Generated by Django 4.2.1 on 2023-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_alter_project_description_alter_project_developers_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_title_8f019f_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title', 'description'], name='project_title_840f44_idx'),
        ),
    ]
